
#debug: true

management:
  endpoints:
    web:
      exposure:
        include: "env, info, health, loggers"
        #include: "*"
  endpoint:
    env:
      show-values: "never"
    health:
      show-details: "never"

greeting:
  word: "Hallo"
  name: "${greeting.word} Dave"

droid:
  id: "B28"
  description: "This is simple droid"